### ISSUE TITLE
Adapt Openshift Build Process

### ISSUE THREAD

**Issue by Montecito** [Gepardec/Hogarama#110]
As a DevOps Enginner I want a build process (on openshift) with automated tests and tagged containers so that
- resulting artifact is at least unit tested for every commit
- final docker container gets tagged if tests are successful

**Acceptance Criteria:**
- [ ] Build process includes executed tests
- [ ] Tag tested containers with "tested"
- [ ] Only deploy tagged containers "tested" in dev environment

**Tasks**
- [x] Write a Unit Test
- [x] Check if S2I process allows activation of Unit tests && Activate tests in openshift S2I build 
- - [ ] else: Configure a pipeline build
- [x] Tag container with "tested" after successful test.
- - [ ] Check if S2I allows tagging, or if pipeline build is required
- [x] Configure deployment config/update trigger for hogarama-development so that only "tested" containers will be deployed
- [x] Test if a wrongly tagged container will be deployed
- [x] Adapt templates
- [x] Adapt release-pipeline

**Comment by cchet** [comment]
Release could be done via
- Use latest tag as image stream tag used by deployment configurations and import image stream after docker image release and trigger deployment
- Add new image stream tag with new version and modify deployment config to use new version and trigger deployment

Jenkins pipelines are Openshift Pipelines. 
Openshift just has own views for the jenkins pipelines and creates a jenkins instance where a pipelines job gets created.

**Comment by cchet** [comment]
For the Liwest project, I have created a more complex Jenkinsfile. I think we should take a look there.

**Comment by hwirnsberger** [comment]
Issue postponed, will be discussed after Deployment Strategy Meeting

**Comment by sjutz** [comment]
S2I process allows the activation of Unit-Tests: Add an environment variable 'MAVENARGS' with the following value (no --DskipTests):
` -e -Popenshift -Dcom.redhat.xpaas.repo.redhatga package -Djava.net.preferIPv4Stack=true`

**Comment by sjutz** [comment]
Hogajama-Image can be tagged with 'tested' by adapting the BuildConfig.
Performed tests:
- [x] When tests fail, build fails -> no new image.
- [x] When image is tagged with wrong tag, eg latest, no deployment is triggered
