### ISSUE TITLE
Pipeline Release Button for production

### ISSUE THREAD

**Issue by Montecito** [Gepardec/Hogarama#113]
As a product owner I want a realease button so that releasing to production can be easily achieved through button click.

**Acceptance Criteria**
- [ ] There is a Button in Pipeline for product owner
- - [ ] Container is tagged with "production" tag
- - [ ] Container will be deployed to production

**Tasks**
- [ ] @Montecito add documentation how to add a pipeline release button
- [x] Configure Pipeline to show release button
- [x] Press the button && test if it tags the container with "production"
- - [x] Check production environment for deployed containers (only "production" allowed)

**Comment by cchet** [comment]
We can implement two pipelines.
1. Pipeline for building, testing, releasing (artifacts to maven, docker image to docker hub) and creating a staging environment. (Could create staging environment for feature branches as well)
2. Pipeline for releasing hogarama to a productive environment.

Inspired from git flow:
Development -> Staging (start Release) -> Fix issues on release -> Productive release (finish Release)

**Comment by Montecito** [comment]
Currently we do not have required permissions on ITandTEL Openshift environment.
ITandTEL is working on the issue and we will have more information next week.

If they cannot fix this issue I prepared a work around, but I want to wait to introduce the workaround to PO until we have more information.

**Comment by Montecito** [comment]
Besides docu this feature is ready :-D

**Comment by Montecito** [comment]
Docu is available at:
https://github.com/Gepardec/Hogarama/wiki/Jenkins#jenkins-pipelines
