### ISSUE TITLE
Create production project on ITandTEL

### ISSUE THREAD

**Issue by Montecito** [Gepardec/Hogarama#114]
As a product owner I want a production stage so that I can seperate development from production operation.

**Acceptance Criteria**
- [x] There is a project on ITandTEL called hogarama production
- [x] There is a template for hogarama 
- - [x] without build configuration 
- - [x] and with configured production image streams (label tested images with "production")

**Tasks**
- [x] Create Project on ITandTel With name hogarama-production
- [x] Rename Project Hogarama to hogarama-dev
- [x] reconfigure Test Habaramas
- [x] Take existing 1024Tage demo templates an adjust the imagestream tags
- [x] import templates onto hogarama-production

**Comment by b0x1** [comment]
I think it's impossible to rename a project, thus we have to do something akin to "oc export -a | oc create -f -", but the PVC etc cannot be migrated. We need a backup, if we want to rename the project hogarama to hogarama-dev.

**Comment by b0x1** [comment]
- Created new project named hogarama-production.
- Bootstrap new environment with Templates/make-hogarama.sh.
- Change Hogajama ImageStream label from latest to production.

**Comment by ludwigSteindl** [comment]
Reviewed and done
