### ISSUE TITLE
Habaramas at home

### ISSUE THREAD

**Issue by Montecito** [Gepardec/Hogarama#115]
As a product owner I want at least 4 habaramas in production (office vienna, linz + 2 @ home) so that we have real world conditions.

**Acceptance Criteria**
- [ ] Four preinstalled raspberries + sensors
- [ ] Raspberries installed and configured at specified locations
- [ ] Raspberries sending data to production environment

**Tasks**
- [x] create a shopping list
- [x] order parts
- [x] assemble everything
- [x] install the software with ansible
- [ ] test setup with hogarama-development stage
- - [ ] configure it with guide from #116 
- [ ] reset the configuration
- [ ] distribute habaramas
- [ ] find 4 people who will setup the hardware and install the habarama software. 
- [ ] setup with hogarama-production stage
- - [ ] configure it with guide from #116

**Comment by fhochleitner** [comment]
done for two raspberry pi's with in-house devs. 
open: let 4 external/non-devs setup a habarama

**Comment by fhochleitner** [comment]
blocked by Issue #137

**Comment by fhochleitner** [comment]
depends on #117

**Comment by fhochleitner** [comment]
@ErhardSiegl with the official end of HogaramaGoesLinz/World project this issue should be closed in my opinion
