### ISSUE TITLE
Create Documentation for DIY home setup

### ISSUE THREAD

**Issue by Montecito** [Gepardec/Hogarama#116]
As a Hogarama User I want a how to setup guide for habarama so that I can easily install and setup a habarama at home without any special prior knowledge.

**Prerequisite**
Preconfigured hardware.

**Acceptance Criteria**
- [ ] There is is wiki article describing the DIY habarama setup for home users
- - [ ] how to install the software
- - [ ] how to configure the software 
- - [ ] how to check if you did everything right
- - [ ] troubleshooting guidelines

**Tasks**
- [ ] check existing documentation
- [ ] create wiki page and add to navigation, if not already there
- [ ] write documentation
- [ ] test it with someone who never configured a habarama.

Further setup #117

**Comment by AdrianFarmadin** [comment]
I have update WIKI for setup.

Pages remaining:
* https://github.com/Gepardec/Hogarama/wiki/Raspberry

@Gepardec/developers can someone review https://github.com/Gepardec/Hogarama/wiki/Habarama Wiki page and it's subpages?
