### ISSUE TITLE
Integration Tests for Hogarama

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#119]
As a developer i want to have integration tests so that I can be sure our whole system works.

**Acceptance Criteria**
- [ ] there is a stage in jenkins pipeline where test results are shown
- [ ] integration tests fire against a ci environment in openshift
- [ ] image is taged with it-tested
- [ ] only it-tested taged container are deployed in development stage.

**Tasks**
- [ ] plz define in sprint planing 2
