### ISSUE TITLE
Measurement graph last 30 recrods

### ISSUE THREAD

**Issue by awagenhoffer** [Gepardec/Hogarama#120]
As a user I want, that the measurement graph shows the last 30 records  that I see only the newest records.

**Acceptance Criteria**
- [x]  The time window shows only the last 30 records for the day
- [x] At the "MESSWERTE AM" shows the last day from the last 30 records 

**Tasks**
- [x] The developer should fix, that the JavaScript take the first 30 records from the first sensor, independent from other records.
