### ISSUE TITLE
Canary Releases / Rolling Deployments

### ISSUE THREAD

**Issue by GuenterPirklbauer** [Gepardec/Hogarama#123]
As a user i want to see a canary release / rolling deployment / blue-green-deployment (one or two of them to be chosen) 

**Acceptance Criteria**
- [ ] precondition: 2 pods with version 1. operator deploys version 2 of software (2 additional pods with version 2), user can test version 2 (e.g. every second request is connected to version version 2) (canary release)
- [ ] precondition: 10 pods with version 1. operator deploys version 2 of software, user can see / test that pods will be exchanged with version 2 (rolling deployment) 
- [ ] precondition: 2 pods with version 1. operator deploys version 2 (2 additional pods) of software, user can see / test version 2 via extra url (blue/green)

**Tasks**
- [ ] In sprint planing 2 the developer should create a list of tasks to solve this issue
