### ISSUE TITLE
Watering the plant via mobile phone

### ISSUE THREAD

**Issue by GuenterPirklbauer** [Gepardec/Hogarama#124]
As a user i want to water the plant via mobile phone.

**Acceptance Criteria**
- [ ] User gets UI on mobile phone via url, plant and watering can will shown.
- [ ] User can water the plant via mobile phone.
- [ ] User can see rising humidity graph

**Tasks**
- [ ] In sprint planing 2 the developer should create a list of tasks to solve this issue

**Comment by GuenterPirklbauer** [comment]
Relates to #82
