### ISSUE TITLE
Copy data into history collection

### ISSUE THREAD

**Issue by awagenhoffer** [Gepardec/Hogarama#130]
As a user want to get the data in the hogajama-chart so that I don't need to wait. 
Info: It takes long, because the database is too big.

![toolangsam](https://user-images.githubusercontent.com/17886507/36580793-023e414e-186a-11e8-90bb-fe7948b6680c.png)

**Acceptance Criteria**
- [ ]  Request pro sensor takes less then 100ms

**Tasks**
- [ ]  Create a history collection for the data
- [ ]  Create script, that copy the data into history collection and delete from habarama collection

**Comment by ErhardSiegl** [comment]
Closing because included #106

**Comment by fhochleitner** [comment]
blocked by #162
