### ISSUE TITLE
Raspberry PI mocks hosted as openshift service - GUI

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#134]
**As presenter of Hogarama demos I want an easy way to simulate data coming from raspi without setting up a raspi in order to show the main features of Hogarama.** 

**Acceptance Criteria**

- [x] There exists a web-page where you can send sensor-data to AMQ with mouse clicks

**Tasks**

- [x] Create a GUI which can execute the jar from story #82 
- [x] gui should contain following features/buttons/fields:
- - [x] Plus Button -> adds +10 to current value (Default is 50)
- - [x] Minus Button -> adds -10 to current value
- - [x] Start Button -> continues sending data with current value
- - [x] Stop Button -> ... yeah ... stop sending data.
- [x] Create an Uber Jar with wildfly swarm an deploy it in a new container.
- [x] data should be sent to AMQ in the current project.
- [x] Make "type" and "name" of plant adaptable in GUI
