### ISSUE TITLE
Support various sensor types

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#136]
As a user i want to use various sensor types so that I am not restricted in price and quality on one supported product

**Acceptance Criteria**
- [ ] One Raspi can support different sensors without being reconfigured
- [ ] "Not much" coding is involved when a new sensor type in integrated in the project

**Background**
When we bought new moisture-sensors we realised that the new sensors work inverted to the old ones. One kind measures resistance (lower value when more water), the other wetness (higher values with more water). That triggered a discussion how we can support the new sensors. Two solutions come to mind:

1. We send the data as it comes to the server and the server interprets the data depending on the sensor type.

Both variants have pros and cons. The first is more straight forward, the second more flexible. The second would lead to performance-problems if the component that reads the data would have to do all the transformation-logic. So the second would lead to some variant of an [Event Sourcing Architecture](https://martinfowler.com/eaaDev/EventSourcing.html).

**Solution hint**
Send raw data to the server. Implement a data interpreter to evaluate different sensor types, which interpret sensor data by type.

Currently the plant.py script is configured to work with the newer sensors. It should be adapted to send raw data which will be handled on the server depending on the sensor type that gets sent to AMQ together with the values. 

**Tasks**
- [ ] In sprint planing 2 the developer should create a list of tasks to solve this issue

**Comment by ErhardSiegl** [comment]
See https://github.com/Gepardec/Hogarama/wiki/Sensors#adding-new-sensor-types
