### ISSUE TITLE
Redesign of Habarama Setup

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#137]
As a user, I want an easy way of setting up my personal Habarama without having to adapt 4 different files. 

**Acceptance Criteria** 

- [x] There is only one single file that needs to be adapted which holds all variables required for the setup of a Habarama unit
- [x] There are multiple roles available, depending on how far the Raspberry Pi is already configured

**Background**

Currently, there are 4 different files that need to be changed in order to successfully configure a Raspberry Pi to be integrated in the current Hogarama environment. This setup is simply not user friendly. Therefore, there should be only one file that holds all variables required for the habarama setup guide. 
Additionally, ansible supports the concept of roles which can be harnessed to adapt the setup depending on how far the end-users have already pre-configured their Raspberry Pi unit. 
The following roles come to mind: 

1. full setup - Starts from a fresh Raspberry Pi installation (OS only)
2. habarama setup - The end-user is expected to have previously configured WiFi (but nothing else)
3. minimal habarama setup - The end-user is expected to have previously configured SSH and WiFi connection 

**Tasks**

- [x] Completely redesign the current ansible scripts to support the above-mentioned roles
- [x] Merge all variables that need to be configured in one single file
- [x] Adapt the wiki page accordingly 
- [x] Test the new ansible setup for all three roles

**Comment by fhochleitner** [comment]
implementation is done.
open: adapting the wiki documentation.

**Comment by fhochleitner** [comment]
pull request ready to be reviewed 
@hwirnsberger as discussed
