### ISSUE TITLE
Buy material for water pumps

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#140]
As a developer I want to have all hardware parts to implement operating the water pump. 

**Acceptance Criteria**
- [x] All parts required for operating a water pump are available x2
- [x] There is one hardware set in Linz
- [x] There is one hardware set in Vienna
- [x] Documentation of required parts exists

**Tasks**
- [x] Choose pump
- [x] Order all required parts for 2 pumps/ tell P.O to order parts
- [x] Distribute pump sets to Vienna and Linz

**Comment by fhochleitner** [comment]
add documentation to wiki page. including parts required for habarama (sensor, raspberry, casing, etc.)
