### ISSUE TITLE
Connect pump to hogarama

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#141]
**Acceptance Criteria**
- [x] There is a Habarama unit in Vienna and in Linz that is connected with a water pump 
- [x] There exists a REST-Service that can start the pump, which will run for X seconds. 

**Solution hint**
- Look at current implementation from Pull-Request (@Tharnas )

**Tasks**
- [x] Connect a raspberry pi with a pump (in linz and vienna)
- [x] Control the pump directly via the raspberry pi
- [x] Send message to ActiveMQ to start/stop the pump
- [x] Create a REST-Service that controls the pump of a specific raspberry pi

**Comment by Tharnas** [comment]
see also #146

**Comment by fhochleitner** [comment]
Ticket blocked until we have a solution for the architecture. Will be reopened in an upcoming sprint

**Comment by fhochleitner** [comment]
TODOs: 
- implement proper testing
- activate Validation as soon as mongoDb decided to stop acting like a child in puberty
