### ISSUE TITLE
Update JBoss to support Elytron Subsystem

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#143]
As a developer I want our JBoss to support Elytron for adapted security requirements. 

**Acceptance Criteria**
- [x] JBoss EAP >= 7.1 is running on OpenShift

**Tasks** 
- [x] Configure template to integrate JBoss EAP 7.x on OpenShift hosted by ITandTel. 
- [x] Configure and test the latest JBoss EAP 7.x release on OpenShift

**Comment by fhochleitner** [comment]
@ErhardSiegl is the integration of the JBoss EAP CD image stream mandatory or nice to have. According to @sjutz it is not recommended to be used in production systems and it might be problematic with our standalone.xml which is in our git repo might break with a newer JBoss version.

**Comment by ErhardSiegl** [comment]
Nice to have. We should find a solution for standalone.xml first.
