### ISSUE TITLE
Add Hogarama Bot to google chat

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#152]
As a Developer I want to get notified in google ch@t when something happens on the project in order to be informed about the current progress, if team members need help, and to try out new features

**Acceptance Criteria**
- [ ] There is a chatbot integration for Hogarama in Google Ch@t

**Tasks**
- [ ] Discuss with management options to integrate a bot to google ch@t
- [ ] Implement the chosen solution

**Comment by ErhardSiegl** [comment]
@AdrianFarmadin built a container for Hubot. We might install it on Openshift.
