### ISSUE TITLE
Performance MongoDB JS-GUI

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#162]
**Acceptance Criteria** 
- [x] We know why we have performance issues loading the hogajama-charts.
- [x] We are able to define tickets to solve our performance issues. 

**Tasks**
- [ ] Evaluate technical issues with our  MongoDB regarding its performance
- [ ] Evaluate technical possibilities of MongoDB Performance optimizations

**Solution Hints**
Start the evaluation of technical possibilities with indexes and/or elastic search for MongoDB
(https://docs.mongodb.com/manual/indexes/)

**Comment by Ruhsi** [comment]
The problem wasn't MongoDB but the highcharts-Framework. The response of the MongoDb was at approximately 300ms (tested with 5000 datasets).
The update-Method of highcharts was the problem. It draws every point using svg. Highcharts has a boost-module that draws every point in canvas and transforms it into svg. Thats much faster.
Response times are now (finished drawing every point and displaying whole graph):

| Number of Points  | Response Time in ms |
| ------------- | ------------- |
| 100  | 230  |
| 500  | 540  |
| 2000 | 1900 |
| 3000 | 2800 |
| 5000 | 4600 |

With the normal highcharts-framework the response time of 1000 points was longer than 10sec.

But now the graph can't show more than 5000 points at once. I think because of the canvas and the overlapping of the points and lines. I don't know if displaying more than 5000 points is a Use-Case.

The code can be reviewed and test on the branch **162_performance_mongoD_JS_GUI**
