### ISSUE TITLE
Migrate from Wildfly-Swarm to Thorntail.io

### ISSUE THREAD

**Issue by cchet** [Gepardec/Hogarama#181]
As a developer I want to use the current version of Wildfly-Swarm, which now is called Thorntail.io. An update to Thorntail.io should be done, because the maven group ids have changed from org.wildfly.swarm to io.thorntail, as well as some fixes regarding dirty transitive dependencies have been made. The switch should be easy, because in the best case only the maven groups ids have to be changed. 

**Acceptance Criteria**
- [ ] pom.xml files only references thorntail.io dependencies
- [ ] Services are running with the modified dependencies, and working properly

**Tasks**
- [ ] Find all implementations which use wildfly-swarm
- [ ] Migrate the Wildfly Swarm dependencies to Thorntail.io dependencies in the pom.xml
- [ ] Test if the services can run with Thorntail.io dependencies, and are working properly
