### ISSUE TITLE
Secure queue with Keycloak

### ISSUE THREAD

**Issue by eerofeev** [Gepardec/Hogarama#188]
As a product owner I want be sure, that only authorized users / registered habarames are able to send messages in the queue.

**Tasks**
- [x] Discuss with PO, how to implement security for the messages, that are sent by services (Tech user, admin account) (jboss)
- [x] Discuss with PO, how to implement security for the messages, that are sent by habaramas (Account per user) (raspb)
- [x] Check, how to implement security in ActiveMQ with Keycloak (as identity provider, jboss Module?)
