### ISSUE TITLE
Define components for Habarama

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#198]
As a developer I want to know which components we need and how they will be assembled so I can order and assemble all necessary parts.

**Acceptance Criteria**
- [x] shopping list for all the parts
- [x] total costs of one unit should not exceed € 20 (ideal would be € 10)
- [x] diagram defining how the parts should be assembled
- [x] parts are ordered

**Tasks**
- [x] research which parts we want to use
- [x] make diagram
- [x] order parts

**Comment by ludwigSteindl** [comment]
@ErhardSiegl How many prototypes do we want to build at first? I'd suggest at least 3-4. We should vary the components, so we have different versions of IoT-Devices?

**Comment by ludwigSteindl** [comment]
Basically, we need the following parts:

- Arduino-based Microcontroller (i.e. Arduino, Sparkfun, Adafreuit, Teensy etc.)
- Wifi board (if not already integrated in microcontroller)
- alternatively, bluetooth board (if not already integrated in MC)
- Lipo charger (if not already integrated in MC)
- Lipo battery

**Comment by ludwigSteindl** [comment]
@johannesr124 @rfischerGep  https://www.exp-tech.de/plattformen/ is a very good starting point for the web research.

**Comment by ludwigSteindl** [comment]
alternatively: https://electronics.semaf.at/startseite

**Comment by rfischerGep** [comment]
**Prototyp 1 - MCU-ESP-WIFI**

Arduino-based Microcontroller (i.e. Arduino, Sparkfun, Adafreuit, Teensy etc.)
- NodeMCU-v2-ESP8266	
		https://electronics.semaf.at/NodeMCU-v2-ESP8266 (10€)

Wifi board (if not already integrated in microcontroller)
- included in NodeMCU-v2-ESP8266

Lipo charger (if not already integrated in MC)
- Adafruit Mini Lipo w/Mini-B USB Jack - USB LiIon/LiPoly charger (7.44€)
		https://www.exp-tech.de/module/stromspannung/5819/adafruit-mini-lipo-w/mini-b-usb-jack-usb-liion/lipoly-charger?c=1439

Lipo battery
- LiPo Akku 1400mAh (3.7 V, 2 mm JST) (9.95€)
		https://www.exp-tech.de/zubehoer/batterien-akkus/lipo-akkus/7250/lipo-akku-1400mah-3.7-v-2-mm-jst
- LiPo Akku 2200mAh (3.7 V, 2 mm JST) (5.95€)
		https://www.exp-tech.de/zubehoer/batterien-akkus/lipo-akkus/7391/lipo-akku-2200mah-3.7-v-2-mm-jst

Costs: ~25€

**Comment by rfischerGep** [comment]
**Prototyp 2 - MCU-ESP32-WIFI-BT**

Arduino-based Microcontroller (i.e. Arduino, Sparkfun, Adafreuit, Teensy etc.)

- SBC-NodeMCU-ESP32
  https://www.conrad.at/de/p/entwickler-platine-sbc-nodemcu-esp32-1656367.html (10.99€)

Wifi board

- included in Microcontroller

Bluetooth board

- included in Microcontroller

Lipo charger (if not already integrated in MC)
- Adafruit Mini Lipo w/Mini-B USB Jack - USB LiIon/LiPoly charger (7.44€)
		https://www.exp-tech.de/module/stromspannung/5819/adafruit-mini-lipo-w/mini-b-usb-jack-usb-liion/lipoly-charger?c=1439

Lipo battery

- LiPo Akku 1400mAh (3.7 V, 2 mm JST) (9.95€)
		https://www.exp-tech.de/zubehoer/batterien-akkus/lipo-akkus/7250/lipo-akku-1400mah-3.7-v-2-mm-jst
- LiPo Akku 2200mAh (3.7 V, 2 mm JST) (5.95€)
		https://www.exp-tech.de/zubehoer/batterien-akkus/lipo-akkus/7391/lipo-akku-2200mah-3.7-v-2-mm-jst

Costs: ~26€

**Comment by ludwigSteindl** [comment]
Alternatives:
WEMOS - Stackable Micro-controller and shields
Micro Controller: https://www.exp-tech.de/plattformen/esp8266/entwicklungsboards/8898/wemos-d1-mini?c=1017
Battery Shield: https://www.exp-tech.de/plattformen/wemos/9153/wemos-battery-shield?c=1017
Relay Shield: https://www.exp-tech.de/plattformen/wemos/9149/wemos-relay-shield?c=1017 

NodeMCU
Micro Controller: https://www.exp-tech.de/module/wireless/wifi/6534/nodemcu-v2-lua-based-esp8266?c=1017 

Lipo Batteries: I'd suggest the use of ~2000mAh cells for initial testing. Costs should be around 5-7€.

A WEMOS Sensor Unit would be ~16€ total (incl. Lipo-Cell)
A WEMOS Actor Unit would be ~10€ + pump (needs to be 5V) + USB power bank for pump (also supplies micro controller)

**Comment by ludwigSteindl** [comment]
@rfischerGep as discussed, please write a shopping list

**Comment by ludwigSteindl** [comment]
@rfischerGep as discussed, please take a look at amazon, may be some of the missing components can be found on amazon.

**Comment by patholzer** [comment]
@ludwigSteindl What is the current state of this issue? Is it ready to close?
