### ISSUE TITLE
Find suitable power supply for Habaramas

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#200]
As a product owner, I want the Habaramas to be battery powered, so that they can be used remotely without the need of an on-premise power supply.

**Acceptance Criteria**
- [ ] power supply is small (TODO: define max. size)
- [ ] power supply lasts at least 6 months
- [ ] costs do not exceed (TODO: define max. price)

**Tasks**
- [x] research
- [ ] test
- [ ] optimize

**Comment by ErhardSiegl** [comment]
The question is whether I need a power supply only for a sensor or also for an actor (pump).

**Comment by ludwigSteindl** [comment]
The battery life strongly depends on the measuring interval.

**Comment by ludwigSteindl** [comment]
Determine size and costs in grooming

**Comment by sjutz** [comment]
@ludwigSteindl @rfischerGep status?

**Comment by SabrinaPloner** [comment]
@ludwigSteindl @rfischerGep status?
