### ISSUE TITLE
Make threshold and duration of watering configurable

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#205]
As a user I want the threshold and duration of watering to be configurable in the GUI so that different plants get exactly the amount of water they need.

**Acceptance Criteria**
- [ ] Duration and threshold of watering can be set in the GUI for each plant and pump
- [ ] Duration is stored in the database
- [ ] Threshold is stored in the database

**Depends on**

- #356

**Tasks**
- [ ] ...
