### ISSUE TITLE
Angular-Prototype

### ISSUE THREAD

**Issue by sjutz** [Gepardec/Hogarama#206]
As a product owner I want to have an Angular prototype so I can see that it works in combination with keycloak and backend.

**Acceptance Criteria**
- [x] prototype exists which runs locally and on Openshift
- [x] prototype can display sensor names
- [x] access for authenticated users only
- [x] prototype is implemented in Angular

**Tasks**
- [x] create login page
- [x] communicate with keycloak (via REST?)
- [x] create page displaying all sensor names, username and logout-button
- [x] WS-security for REST-service
- [x] deploy on Openshift

**Comment by csalmhof** [comment]
https://github.com/eirslett/frontend-maven-plugin
