### ISSUE TITLE
Log-In with existing credentials

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#209]
As an user I want to log in with my existing credentials so that I can get a valid authentication response.

**Acceptance Criteria**
- [x] User can log in with his/her credentials
- [x] There is a link to secured login service. If user is not authenticated, he/she will be redirected to keycloak login page.
- [x] There ist a user service returning initial user data.

**Tasks**
- [x] Figure out appropriate architecture (How to integrate keycloak with REST? Is it necessary? -> JBoss Module for Keycloak?) -> Use standard redirect mechanism of keycloak + Jboss Module for Keycloak
- [x] Implement backend service. 
- [x] Front-End reacts to backend response (Displays user name and sensors)

**Hint**
Keycloak already exists! See OpenShift instance

**Comment by sjutz** [comment]
Linked to #206

**Comment by eerofeev** [comment]
After research we decided to use the default redirect mechanism of keycloak. Therefor some tasks have been updated.
