### ISSUE TITLE
Register a new user with username and password

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#210]
As a new user I want register with a username and password so that I can use the existing system.

**Acceptance Criteria**
- [x] ~~Register-Page~~
- [x] ~~Register-Backend~~
- [x] Login with registered credentials is possible

**Tasks**
- [x] Figure out appropriate architecture (How to integrate keycloak with REST? Is it necessary? -> JBoss Module for Keycloak?)
- [x] ~~Implement backend service~~
- [x] ~~Create Register-Page~~
- [x] Front-End reacts to backend response

**Comment by sjutz** [comment]
Linked to #206

**Comment by eerofeev** [comment]
Consider following features:

- CAPTCHA
- Activation via confirmation e-mail

**Comment by eerofeev** [comment]
After research we decided to use default authentication / registration mechanisms of keycloak via redirects.
