### ISSUE TITLE
Login with Google-Account

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#211]
As a user I want to use my Google Account credentials so that I login without further registration.

**Acceptance Criteria**
- [x] user can login with his Google Account

**Tasks**
- [x] Research
- [x] Extend login page
- [x] Connect with Keycloak

Extends #209

**Comment by ErhardSiegl** [comment]
@patholzer See also issues with lable "Topic Security" https://github.com/Gepardec/Hogarama/issues?utf8=%E2%9C%93&q=label%3A%22Topic+Security%22+

**Comment by sjutz** [comment]
Linked to #206
