### ISSUE TITLE
Secure existing backend services via Keycloak

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#212]
As an architect I want the backend services to be secured by Keycloak so that only authorized users can call the backend services.

**Acceptance Criteria**
- [x] backend services are secured by Keycloak

**Tasks**
- [x] ~~define and configure roles~~
- [x] secure backend-services

**Comment by sjutz** [comment]
Linked to #206
