### ISSUE TITLE
Minimal executable angular prototype

### ISSUE THREAD

**Issue by sjutz** [Gepardec/Hogarama#218]
As a developer I want to have a minimal executable angular prototype so that I use this as a starting point.

**Acceptance Criteria**
- [x] minimal executable angular prototype exists
- [x] prototype runs locally
- [x] prototype is deployable on Openshift

**Tasks**
- [x] create minimal executable angular prototype
- [x] build prototype with maven
- [x] deploy prototype on Openshift

**Comment by sjutz** [comment]
Linked to #206

**Comment by patholzer** [comment]
- minimal executeable angular prototype is integrated into the maven ecosystem
- we can build and deploy it locally 
- runnable on openshift, see project playground - hogajama
https://manage.cloud.itandtel.at/console/project/57-playground/browse/dc/hogajama
