### ISSUE TITLE
Display sensor names

### ISSUE THREAD

**Issue by sjutz** [Gepardec/Hogarama#219]
As a user I want to see all sensor names so that I have an overview of the available sensors.

**Acceptance Criteria**
- [x] page exists displaying all sensor names
- [x] only authorized users can call backend service
- [x] on unauthorized access, empty page is shown

**Tasks**
- [x] secure backend service
- [x] create angular page to show the sensor names
- [x] connect angular with backend service
- [x] handle unauthorized access

**Comment by sjutz** [comment]
Linked to #206

**Comment by sjutz** [comment]
Linked to #206

**Comment by MauriceNino** [comment]
test

**Comment by MauriceNino** [comment]
Angular page to show all sensor name created. Connection to backend service would work (technically), but hogajama-rs is not deployed in 57-playground.
