### ISSUE TITLE
Implement a demo operator

### ISSUE THREAD

**Issue by cchet** [Gepardec/Hogarama#226]
We want to have a demo operator, which is capable of provisioning parts of the Hogarama System to prove that operators can be used for Hogarama.

**Acceptance Criteria**
- [ ] Operator manages MongoDB
- [ ] Operator manages EAP
- [ ] Operator manages Keycloak conditionally (oauth=true)
- [ ] Operator manages Mock-Services conditionally (mocked=true)

**Tasks**
- [x] Setup Operator Project
- [x] Implement management of MongoDB
- [ ] Implement management of Hogajama
- [ ] Implement management of EAP
- [ ] Implement management of Keycloak
- [ ] Implement management of Mock-Services

**Comment by ErhardSiegl** [comment]
See #227 for Mock-GUI problem.

**Comment by cchet** [comment]
We need to resolve the issue that minishift isn't capable of pulling from redhat registry because of authentication issues.

**Comment by ErhardSiegl** [comment]
Is there a problem description for the authentication issue?
