### ISSUE TITLE
Edit user settings 

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#229]
As a user I want to be able to configure my name, email, and password so that I can change my account information without needing to create a new one. 

**Acceptance Criteria**
- [ ] username is configurable
- [ ] email is configurable
- [ ] password is configurable

**Tasks**
- [ ] find out how to communicate with keycloak
- [ ] rate potential solutions and decide which one to implement
- [ ] implement functionality
