### ISSUE TITLE
Create technical infrastructure/architecture for sensor configuration

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#230]
As a developer I want to to have a technical infrastructure so that I am able to implement additional functionality .

**Acceptance Criteria**
- [ ] microcontrollers send unique identifier
- [ ] database structure for mapping ids with user data exists
- [ ] REST/domain services are available to configure microcontrollers
- [ ] ensure that old raspberry units are still working

**Tasks**
- [ ] define tasks in sprint planning II
