### ISSUE TITLE
Implement custom design for Login Page

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#231]
As a user I want to have a visually pleasing experience when accessing the login page so I have a consistent experience when interacting with the web-application.

**Acceptance Criteria**
- [ ] Design with the overall Gepardec/Hogarama CI is implemented on the login page

**Tasks**
- [ ] create design see #207 
- [ ] redesign current login page design
