### ISSUE TITLE
Design and implement domain model 

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#241]
As an architect I want to have a database and domain model which can handle all the specified user stories. 

**Tasks**
- [x] Design domain model based on the defined user stories
- [x] Create DB schema
- [x] Flyway integration
- [x] Create JPA Entities 

See: User Stories Google Chat and miro
https://miro.com/app/board/o9J_kwgJaik=/

**Comment by ErhardSiegl** [comment]
A learning from our loooong discussion last week was that we should not attempt to design a domain modell for all user stories upfront, but design and implement the domain modell incrementally for each user story.

**Comment by patholzer** [comment]
https://www.baeldung.com/hibernate-inheritance
