### ISSUE TITLE
Define a rule for a unit

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#247]
As a user I want to configure a rule so that I can water my plants depending on the moisture value measured by the sensor.

**Acceptance Criteria**
- [ ] user can configure the threshold and duration via the GUI. 
- [ ] When the threshold for sensor A < x, pump B is triggered for a duration of y seconds

**Tasks**
- [ ] In sprint planing 2 the developer should create a list of tasks to solve this issue
