### ISSUE TITLE
Epic - Pumps

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#248]
**User Storys**
*Goals*
- [ ] Add and edit an actor (pump) #301
- [ ] Display actor name on Prometheus graphs #343
- [ ] Manage rule for watering

*No Goals*
- [ ] [GUI] Show dashboard with added pumps #274
- [ ] [GUI] Show detail view of my unit with more configuration option #302
- [ ] [GUI] Start the pump manually for a configurable duration #304

**Tasks**
- [x] REST + Domain Service: add pump #261 
- [ ] Domain Service: start pump for a configurable duration #263
- [ ] REST + Domain Service: get all pumps of a user #261 
- [ ] Security #261 
- [ ] GUI: show pumps of a user #262
- [ ] GUI: add button to start the pump for a configurable duration #263
- [ ] GUI: add pump #262
- [ ] Arduino: connect pump to arduino #264 
- [ ] Integration (Arduino, backend) #264

**Comment by ErhardSiegl** [comment]
Can the pump with the new configuration be integrated into the watering-logic as it works right now with actors? Or will there be an old configuration that works with watering and a new that can be seen and that works manually only?
