### ISSUE TITLE
Sensor administration

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#249]
As a user I want to add a sensor to my configuration so that I can measure the moisture.

**Acceptance Criteria**
- [ ] user can add sensor via GUI
- [ ] user can see his configured sensors
- [ ] moisture of the plant is displayed somewhere (GUI or Grafana or Prometheus or ...)

**Tasks**
- [ ] Connection between keycloak user and user in domain model (add to Db, add Default Unit)
- [ ] Adapt domain model (add flag for default Unit)
- [ ] REST endpoint + service for adding a sensor
- [ ] Habarama, Hogajama: Define SensorDataDTO, Sensor sends his ID + UserId
- [ ] GUI: Add sensor, list sensors of user, (display sensor data)
- [ ] Security: User should only be allowed to send sensor data for his sensor, sensor should get the userId at registration
