### ISSUE TITLE
Add user

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#250]
As a developer I want that a owner and default unit is added when the user registers.

**Acceptance Criteria**
- [x] when a new user is registered, a owner is stored in the DB with the keycloak-user-id
- [x] a default unit is added to the owner

**Tasks**
- [x] Interceptor that checks if owner is already in database, otherwise 
  - [x] add a new owner with keycloak-user-id
  - [x] add default-unit
- [x] Integration tests
