### ISSUE TITLE
Adapt domain model

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#251]
As a developer I want add a flag for the default Unit to the domain model so that I can identify the default unit of a user.

**Acceptance Criteria**
- [x] Unit has a Boolean field defaultUnit NOTNULL DEFAULT false
- [x] Domain model contains the new field

**Tasks**
- [x] Write flyway script
- [x] Adapt domain model
- [x] Set all necessary NOTNULL constraints
- [x] Adapt entity in Hogajama
