### ISSUE TITLE
[WS] Add sensor

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#252]
As a user I want to have a Web Service to add a sensor so that I can add a sensor.

**Acceptance Criteria**
- [x] REST endpoint exists for adding a sensor
- [x] Sensor is added after calling the REST endpoint
- [x] No duplicate of technical sensor id

**Tasks**
- [x] REST endpoint
- [x] Domain service
- [x] Generic Dao for CRUD operations
- [x] Integration tests
- [x] add sensor type entities via flyway
- [x] refresh SensorTypeCache on missing id
