### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#253]
As a architect I want to have an exception handling so that I all exceptions are handled correctly.

**Acceptance Criteria**
- [x] backend: exceptions should be handled in a standardized way (exceptions are caught, transaction rollback)
- [x] error messages should be displayed by the GUI in a standardized way
- [x] exceptions should be logged
- [x] HTTP Status is set correctly
- [x] Error messages are contained in the ResponseDTO

**Tasks**
- [x] backend: Interceptor 
- [x] frontend: Exception handling
