### ISSUE TITLE
Refactor SensorDataDTO

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#254]
As a developer I want to use a refactored SensorDataDTO so that I have all necessary data.

**Acceptance Criteria**
- [ ] Definition of SensorDataDTO exists
- [ ] SensorDataDTO contains device id
- [x] Version number is increased to v2
- [ ] Arduino sends refactored SensorDataDTO (v2)
- [ ] Raspberry Pi still sends SensorDataDTO v1
- [ ] Hogajama uses refactored SensorDataDTO (v2)
- [ ] SensorDataDTO contains security token (see https://github.com/Gepardec/Hogarama/issues/259)

**Tasks**
- [ ] Define SensorDataDTO
- [ ] Adapt Arduino to send new SensorDataDTO
- [ ] Adapt Hogajama to use the new SensorDataDTO
