### ISSUE TITLE
[WS] Get and add pump

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#261]
As a user I want get or add a pump so that I can water my plants.

**Acceptance Criteria**
- [x] REST Endpoint for adding a pump
- [x] REST Endpoint for get all pumps for current owner
- [x] Endpoints are secured by keycloak

**Tasks**
- [x] DAO
- [x] Domain Service
- [x] REST Endpoints
- [x] Keycloak Configuration
