### ISSUE TITLE
[GUI] Get and add pump

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#262]
As a user I want get or add a pump so that I can see my pumps or add a new one

**Acceptance Criteria**
- [ ] Add pump via GUI
- [ ] Show all pumps for current owner on GUI

**Tasks**
- [ ] Show list / table / .. for all unassigned pumps (belong to default unit)
- [ ] Add a pump

**Comment by mk-gepard** [comment]
@mhofmann-gepardec ich hab den issue auf erledigt gesetzt, er kommt doppelt vor ...
