### ISSUE TITLE
Trigger pump manually for a given duration

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#263]
As a user I want to trigger my pump manually so that I can water my plants for a given duration.

**Acceptance Criteria**
- [ ] Do not use rule logic to solve this issue 
- [ ] guarantee downwards compatibility
- [ ] Trigger pump via GUI (e.g. button and text field for duration)
- [ ] Pump waters for duration on command

**Tasks**
- [ ] Create architecture concept
- [ ] Add gui elements to pump overview or detail page 
- [ ] Rest endpoint
- [ ] Domain service
