### ISSUE TITLE
[HW] Pump integration

### ISSUE THREAD

**Issue by patholzer** [Gepardec/Hogarama#264]
As a user I want to have an integrated pump so that I can water my plants.

**Acceptance Criteria**
- [ ] assembled pump hardware exists
- [ ] pump is integrated in hogarama ecosystem 
- [ ] pump retrieves watering events and triggers watering

**Tasks**
- [ ] assemble microcontroller
- [ ] connect to MQTT
- [ ] interpret watering events
- [ ] (nice-to-have) fritz diagram
