### ISSUE TITLE
Login page for unit management 

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#271]
AS A user I WANT TO login with my credentials SO THAT I can use Hogarama.

**Acceptance Criteria**
- [ ] Login page looks like https://sketch.cloud/s/ng344/a/MAaWy3
- [ ] Redirect on Login Page from https://hogajama-57-hogarama.cloud.itandtel.at/ (klick on UNIT-MANAGEMENT)
- [x] User can login with his e-mail and password
- [x] 'Forgot password' is implemented
- [x] Google Authentication is implemented

**Tasks**
- [ ] ...
