### ISSUE TITLE
[GUI] Show dashboard with added pumps

### ISSUE THREAD

**Issue by mk-gepard** [Gepardec/Hogarama#274]
As a user I want to see a dashboard view with added pumps so that I can manage my added pumps.

**Acceptance Criteria**
- [ ] Dashboard view with added pumps  looks like https://sketch.cloud/s/ng344/a/z25bxr 
- [ ] Dashboard shows plants (units) with added pumps
- [ ] Dashboard shows all unassigned (default unit) pump

**Tasks**
- [ ] ...

**Comment by mk-gepard** [comment]
ist doppelt
