### ISSUE TITLE
[GUI] Add a new sensors

### ISSUE THREAD

**Issue by mk-gepard** [Gepardec/Hogarama#275]
As a user I want to add a new sensor to my plant (units) so that I can edit this.

**Acceptance Criteria**
- [ ] The user can add a new sensor from empty dashboard like this: https://sketch.cloud/s/ng344/a/58zD2y
- [ ] The user can add a new sensor from a dashboard like this: https://sketch.cloud/s/ng344/a/z25bxr
- [ ] The user can add a new sensor from the detail view of a plant (item) like this: https://sketch.cloud/s/ng344/a/z25bxr

**Tasks**
- [ ] ...
