### ISSUE TITLE
Merge IoT-Branch into master

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#281]
The branch hogarama_goes_IoT should be merged back to master.

**Acceptance Criteria**
- [ ] the branch hogarama_goes_IoT is merged into the maser
- [ ] Working setup on ITandTel Openshift cluster
- [ ] Working setup on local Openshift cluster
- [ ] ...

**Tasks**
- [ ] Merge

**Comment by fhochleitner** [comment]
can we please adapt the acceptance criteria that it includes a working setup on itandtel openshift cluster as well as local setup?

**Comment by ErhardSiegl** [comment]
It should be clear, but currently working features should keep working.
