### ISSUE TITLE
Set up Build Pipeline (including integration tests)

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#282]
A build pipeline should be set up which builds and tests the artefacts.

**Acceptance Criteria**
- [ ] Pipeline builds artefacts
- [ ] Unit Tests are executed
- [ ] Integration tests are executed
- [ ] ...

**Tasks**
- [ ] ...
