### ISSUE TITLE
Add and edit an actor (pump)

### ISSUE THREAD

**Issue by mk-gepard** [Gepardec/Hogarama#301]
AS a user 
I WANT to add and edit a pump via (Test)-GUI 
SO THAT I can easily change the names to match new physical configurations.

**Acceptance Criteria**
- [x] The added pump has a name and a (default) unit 
- [x] If I don't change my configurations, it should still work (no migration necessary) (@patholzer see comment blow)

**Hint**
Mind the name of the topic that is used for watering! Use unit_name/device_id as topic name(?)
If actor is not configured in db, use ort/actor_name as it is now.

**Tasks**
- [x] Create actor table 
- [x] Create domain-service(s) for actor
- [x] Create REST-API and service
- [x] Create (Test) GUI

**Comment by patholzer** [comment]
As discussed with @ErhardSiegl 
"If I don't change my configurations, it should still work (no migration necessary)" - This acceptance criteria is part of other stories
