### ISSUE TITLE
Show detail view of my UNIT with more configuration option 

### ISSUE THREAD

**Issue by mk-gepard** [Gepardec/Hogarama#302]
AS A user
I WANT to see a detail view of a unit
SO THAT I can see the unit and a list of sensors and pumps 

**Acceptance Criteria**
- [ ] Detail view looks like https://sketch.cloud/s/ng344/a/wRlZ0m/play
- [ ] I can see the name and current value and status of each sensor (connected, not connected)
- [ ] ...

**Not part of this user story**
- Calendar on the right side

**Tasks**
- [ ] In sprint planing 2 the developer should create a list of tasks to solve this issue

**Comment by mk-gepard** [comment]
@ErhardSiegl wie viele Pumpen Sensoren hast du auf deinem raspberry im Garten angeschlossen. Oder hast du gar mehrere Raspberrys im Einsatz.

**Comment by ErhardSiegl** [comment]
Ich habe 4 Sensoren und ein Pumpe angeschlossen. Die Hardware unterstützt 7 oder 8 Sensoren. Pumpen glaube ich 4.
