### ISSUE TITLE
[GUI] Start the pump manually for a configurable duration

### ISSUE THREAD

**Issue by mk-gepard** [Gepardec/Hogarama#304]
AS A user
I WANT to start the pump manually via button on the GUI for a configurable duration
SO THAT I can water my plants manually.

**Acceptance Criteria**
- [ ] Slider for duration 0-5 minutes
- [ ] Watering start button
- [ ] Watering stop button

**Tasks**
- [ ] GUI

**Comment by ErhardSiegl** [comment]
Reason for me: so that I can test/debug my setup.

You don't need a "watering stop" button because watering stops after the given duration. You can only sent watering-events for a given time.

Watering is in seconds. Usually something between 10 an 40 seconds. Input field would be ok as well (better?)

**Comment by eerofeev** [comment]
I would say input vield and few buttons with default values e.g. 10 sec, 30 sec, 1min

**Comment by ErhardSiegl** [comment]
Duplicate of #263
