### ISSUE TITLE
[GUI] Show dashboard with added UNITS, PUMPS or SENSORS

### ISSUE THREAD

**Issue by mhofmann-gepardec** [Gepardec/Hogarama#319]
As a user 
I WANT to see a dashboard view with added UNITS, PUMPS or SENSORS
SO THAT I get an overview over my added UNITS, PUMPS or SENSORS.

**Acceptance Criteria**
- [ ] Dashboard view like this: https://sketch.cloud/s/ng344/a/z25bxr 
- [ ] Dashboard shows UNITS (Plats) with added PUMPS and SENSOR Information
- [ ] Dashboard shows all unassigned (default unit) PUMPS and SENSOR

**Not inlcuded**
- Section "Meine Pflanzen"

**Tasks**
- [ ] ...

**Comment by rfischerGep** [comment]
Info zum Mocken von REST Schnittstellen in Angular:

Json-Server:
https://www.npmjs.com/package/json-server

2 Tutorials:
https://medium.com/@websleengur/mock-data-for-angular-5-applications-with-json-server-part-1-d377eced223b

https://blog.angulartraining.com/fake-your-angular-backend-until-you-make-it-8d145f713e14

**Comment by MauriceNino** [comment]
Have added the units and sensors (and also pumps, but not implemented yet in the TS code) to the dashboard.

Two things:
1) Code could eventually be extracted into own submodules (if that is the approach we want to go with)
2) I didn't use the new page, created by @patholzer because it would be an extra navigation. I didn't delete it yet either, because I don't know if the code written is still relevant. Please let me know or delete it by yourself.

**Comment by patholzer** [comment]
@MauriceNino You can delete my new page if it's unused, thanks!

**Comment by mhofmann-gepardec** [comment]
@MauriceNino Actors are missing under "Nicht zugeordnete Geräte" (test-prototype.component.html), percentages for pumps and sensors don't deliver valuable information, and can be removed.
