### ISSUE TITLE
 Display actor name on Prometheus graphs

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#343]
As a User I want to see the actor name in Prometheus graphs so that the graphs correlate to my setup and make sense.

**Acceptance Criteria**
- [ ] Actor name is shown
- [ ] Prometheus display uses a cache
- [ ] CQRS (command query responsibility separation) is used in code

Hint: http://prometheus-57-hogarama.cloud.itandtel.at/graph?g0.range_input=2h&g0.expr=hogarama_sensor_value&g0.tab=0&g1.range_input=1w&g1.expr=hogarama_watering_events_fired%7Bsensor_name%3D%22GruenerGepard%22%7D&g1.tab=0 

**Tasks**
- [ ] In sprint planing 2 the developer should create a list of tasks to solve this issue

**Comment by fhochleitner** [comment]
Using prometheus console templates might be one way to achieve this: https://prometheus.io/docs/visualization/consoles/

**Comment by ErhardSiegl** [comment]
Interesting feature, but was is meant in this issue, that the labels are set according to actorName and deviceName in unitmanagement like it was done with sensors
