### ISSUE TITLE
Change id from sequence to UUID

### ISSUE THREAD

**Issue by matfa42** [Gepardec/Hogarama#347]
The ID for the entities Actor, Owner, Sensor, and SensorType should be created as an Postgres [uuid-ossp](https://www.postgresql.org/docs/12/uuid-ossp.html) extension in particular with the uuid_generate_v4() function. 

Helpful Links:
[PostgresSQL UUID](https://www.postgresqltutorial.com/postgresql-uuid/)

**Acceptance Criteria**
- [ ] Enity ID should be created as a UUID (e.g.  40e6215d-b5c6-4896-987c-f30f3678f608)

**Tasks**
- [ ] Install uuid-oosp extension (via SQL statement) with helm on container creation 
- [ ] Update current SQL files
