### ISSUE TITLE
Raspberry PI mocks hosted as openshift service - Command-Line

### ISSUE THREAD

**Issue by cchet** [Gepardec/Hogarama#82]
**As developer I want an easy way to simulate data coming from raspi without setting up a raspi in order to test my code on the server-side.** 

**Acceptance Criteria**
- [x] There exists a command-line tool which reads sensor-data from a file and sends it to AMQ

**Tasks**

- [x] Use Java
- [x] Create an executeable jar.
- [x] Create a config file which contains information where and which data is send to AMQ.
- [x] Commandline options can overrule config file.
- [x] Read data from file and send it to AMQ.

**Comment by eerofeev** [comment]
Added [documentation](/Gepardec/Hogarama/wiki/Raspberry-PI-Mocks-CLI)
